name: Android Kernel Action
description: Build android kernel with GitHub Action
author: changhuapeng <changhuapeng@users.noreply.github.com>
branding:
  icon: box
  color: green
inputs:
  arch:
    description: Device architecture
    required: true
  compiler:
    description: Compiler to use
    required: true
  defconfig:
    description: Defconfig to use
    required: true
  image:
    description: Kernel image name
    required: true
  dtb:
    description: dtb image support
    required: true
  dtbo:
    description: dtbo image support
    required: true
  kernelsu:
    description: KernelSU integration
    required: true
  kprobes:
    description: Using Kprobes for KernelSU integration
    required: true
outputs:
  build_date:
    description: Build date and time
    value: ${{ steps.run-action.outputs.build_date }}
  elapsed_time:
    description: Time elapsed from building the kernel in seconds
    value: ${{ steps.run-action.outputs.elapsed_time }}
  hash:
    description: Kernel commit hash
    value: ${{ steps.run-action.outputs.hash }}
  notes:
    description: Text passed from compilation runtime
    value: ${{ steps.run-action.outputs.notes }}
  outfile:
    description: Zip file generated from build
    value: ${{ steps.run-action.outputs.outfile }}
  image:
    description: Kernel image generated from build
    value: ${{ steps.run-action.outputs.image }}
  dtb:
    description: dtb image generated from build
    value: ${{ steps.run-action.outputs.dtb }}
  dtbo:
    description: dtbo image generated from build
    value: ${{ steps.run-action.outputs.dtbo }}
runs:
  using: composite
  steps:
    - name: Run action
      id: run-action
      env:
        ARCH: ${{ inputs.arch }}
        COMPILER: ${{ inputs.compiler }}
        DEFCONFIG: ${{ inputs.defconfig }}
        IMAGE: ${{ inputs.image }}
        DTB: ${{ inputs.dtb }}
        DTBO: ${{ inputs.dtbo }}
        KERNELSU: ${{ inputs.kernelsu }}
        KPROBES: ${{ inputs.kprobes }}
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
